/* Generated by tools/generate.py from schema/vtp1.yaml. Do not edit. */
#ifndef VTP1_GENERATED_H
#define VTP1_GENERATED_H

#define VTP_MAJOR 1
#define VTP_MINOR 0
#define VTP_MIN_ATT_MTU 100

#define VTP_SERVICE_UUID "56545001-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_INFO_UUID "56544301-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_GPS_UUID "56544302-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_CAN_UUID "56544303-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_IMU_UUID "56544304-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_CONTROL_UUID "56544305-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_MONITOR_VALUES_UUID "56544306-5f05-5b56-af87-dcab2baf2522"

/* Device self-description. Read once per connection; never cached across connections. */
#define VTP_INFO_SIZE 24
#define VTP_INFO_OFF_PROTOCOL_MAJOR 0
#define VTP_INFO_OFF_PROTOCOL_MINOR 1
#define VTP_INFO_OFF_CAPABILITIES 2
#define VTP_INFO_OFF_GPS_RATE_HZ 6
#define VTP_INFO_OFF_GPS_MAX_RATE_HZ 8
#define VTP_INFO_OFF_CAN_SUBSCRIPTION_SLOTS 10
#define VTP_INFO_OFF_CAN_MAX_FRAMES_PER_S 12
#define VTP_INFO_OFF_IMU_RATE_HZ 16
#define VTP_INFO_OFF_IMU_MAX_RATE_HZ 18
#define VTP_INFO_OFF_CAN_MAX_PAYLOAD 20
#define VTP_INFO_OFF_CLOCK_FLAGS 21
#define VTP_INFO_OFF_MAX_NOTIFY_BYTES 22

/* One complete position solution. Never split, never paired, never packed. */
#define VTP_GPS_FIX_SIZE 74
#define VTP_GPS_FIX_OFF_SEQ 0
#define VTP_GPS_FIX_OFF_DROPPED 2
#define VTP_GPS_FIX_OFF_VALIDITY 4
#define VTP_GPS_FIX_OFF_T_DEVICE 8
#define VTP_GPS_FIX_OFF_T_UTC 16
#define VTP_GPS_FIX_OFF_LAT 24
#define VTP_GPS_FIX_OFF_LON 28
#define VTP_GPS_FIX_OFF_ALT_MSL 32
#define VTP_GPS_FIX_OFF_ALT_ELLIPSOID 36
#define VTP_GPS_FIX_OFF_VEL_N 40
#define VTP_GPS_FIX_OFF_VEL_E 44
#define VTP_GPS_FIX_OFF_VEL_D 48
#define VTP_GPS_FIX_OFF_HEAD_MOT 52
#define VTP_GPS_FIX_OFF_H_ACC 56
#define VTP_GPS_FIX_OFF_V_ACC 60
#define VTP_GPS_FIX_OFF_S_ACC 64
#define VTP_GPS_FIX_OFF_P_DOP 68
#define VTP_GPS_FIX_OFF_FIX_TYPE 70
#define VTP_GPS_FIX_OFF_NUM_SV 71
#define VTP_GPS_FIX_OFF_FIX_FLAGS 72
#define VTP_GPS_FIX_OFF_EXT_COUNT 73

/* Batch header. Followed by `count` can_record entries. */
#define VTP_CAN_HEADER_SIZE 16
#define VTP_CAN_HEADER_OFF_SEQ 0
#define VTP_CAN_HEADER_OFF_DROPPED 2
#define VTP_CAN_HEADER_OFF_T_BASE 4
#define VTP_CAN_HEADER_OFF_COUNT 12
#define VTP_CAN_HEADER_OFF_FLAGS 13
#define VTP_CAN_HEADER_OFF_RESERVED 14

/* One CAN frame with a device-measured bus-arrival time. */
#define VTP_CAN_RECORD_SIZE 7
#define VTP_CAN_RECORD_OFF_DT 0
#define VTP_CAN_RECORD_OFF_ID 2
#define VTP_CAN_RECORD_OFF_LEN 6

/* Batch header. Followed by `count` evenly spaced imu_sample entries. */
#define VTP_IMU_HEADER_SIZE 20
#define VTP_IMU_HEADER_OFF_SEQ 0
#define VTP_IMU_HEADER_OFF_DROPPED 2
#define VTP_IMU_HEADER_OFF_T_BASE 4
#define VTP_IMU_HEADER_OFF_PERIOD 12
#define VTP_IMU_HEADER_OFF_COUNT 16
#define VTP_IMU_HEADER_OFF_FLAGS 17
#define VTP_IMU_HEADER_OFF_RESERVED 18

/* Sensor-frame acceleration and rotation. Vehicle alignment is the client's job. */
#define VTP_IMU_SAMPLE_SIZE 12
#define VTP_IMU_SAMPLE_OFF_AX 0
#define VTP_IMU_SAMPLE_OFF_AY 2
#define VTP_IMU_SAMPLE_OFF_AZ 4
#define VTP_IMU_SAMPLE_OFF_GX 6
#define VTP_IMU_SAMPLE_OFF_GY 8
#define VTP_IMU_SAMPLE_OFF_GZ 10

/* One page of the channels a device asks for. Followed by `count` monitor_channel entries. */
#define VTP_MONITOR_PAGE_SIZE 6
#define VTP_MONITOR_PAGE_OFF_TOTAL 0
#define VTP_MONITOR_PAGE_OFF_INDEX 2
#define VTP_MONITOR_PAGE_OFF_COUNT 4
#define VTP_MONITOR_PAGE_OFF_RESERVED 5

/* One channel a device asks the client to supply. */
#define VTP_MONITOR_CHANNEL_SIZE 4
#define VTP_MONITOR_CHANNEL_OFF_SLOT 0
#define VTP_MONITOR_CHANNEL_OFF_CHANNEL 1
#define VTP_MONITOR_CHANNEL_OFF_MAX_AGE 3

/* Batch header for a client-to-device value update. Followed by `count` monitor_value entries. */
#define VTP_MONITOR_HEADER_SIZE 4
#define VTP_MONITOR_HEADER_OFF_SEQ 0
#define VTP_MONITOR_HEADER_OFF_COUNT 2
#define VTP_MONITOR_HEADER_OFF_RESERVED 3

/* One value for a slot the device asked for. */
#define VTP_MONITOR_VALUE_SIZE 6
#define VTP_MONITOR_VALUE_OFF_SLOT 0
#define VTP_MONITOR_VALUE_OFF_VALIDITY 1
#define VTP_MONITOR_VALUE_OFF_VALUE 2

/* One page of the CAN subscription table. Followed by `count` can_subscription entries. */
#define VTP_CAN_LIST_PAGE_SIZE 6
#define VTP_CAN_LIST_PAGE_OFF_TOTAL 0
#define VTP_CAN_LIST_PAGE_OFF_INDEX 2
#define VTP_CAN_LIST_PAGE_OFF_COUNT 4
#define VTP_CAN_LIST_PAGE_OFF_RESERVED 5

/* One installed CAN subscription, as the device holds it. */
#define VTP_CAN_SUBSCRIPTION_SIZE 13
#define VTP_CAN_SUBSCRIPTION_OFF_HANDLE 0
#define VTP_CAN_SUBSCRIPTION_OFF_ID 2
#define VTP_CAN_SUBSCRIPTION_OFF_MASK 6
#define VTP_CAN_SUBSCRIPTION_OFF_MODE 10
#define VTP_CAN_SUBSCRIPTION_OFF_ARG 11

/* The envelope of every Control response. Detail follows only when status is ok. */
#define VTP_CONTROL_RESPONSE_SIZE 3
#define VTP_CONTROL_RESPONSE_OFF_OPCODE 0
#define VTP_CONTROL_RESPONSE_OFF_TAG 1
#define VTP_CONTROL_RESPONSE_OFF_STATUS 2

/* The detail of a TIME_SYNC response. Two readings of one clock, so a client can bound its own error. */
#define VTP_TIME_SYNC_SIZE 16
#define VTP_TIME_SYNC_OFF_T_DEVICE_RX 0
#define VTP_TIME_SYNC_OFF_T_DEVICE_TX 8

/* The device's view of the negotiated link. Reported, never negotiated here. */
#define VTP_LINK_PARAMS_SIZE 16
#define VTP_LINK_PARAMS_OFF_VALIDITY 0
#define VTP_LINK_PARAMS_OFF_ATT_MTU 2
#define VTP_LINK_PARAMS_OFF_LL_MAX_TX_OCTETS 4
#define VTP_LINK_PARAMS_OFF_LL_MAX_RX_OCTETS 6
#define VTP_LINK_PARAMS_OFF_CONN_INTERVAL 8
#define VTP_LINK_PARAMS_OFF_PERIPHERAL_LATENCY 10
#define VTP_LINK_PARAMS_OFF_SUPERVISION_TIMEOUT 12
#define VTP_LINK_PARAMS_OFF_PHY_TX 14
#define VTP_LINK_PARAMS_OFF_PHY_RX 15

typedef enum {
    VTP_FIX_TYPE_NONE = 0,
    VTP_FIX_TYPE_DEAD_RECKON = 1,
    VTP_FIX_TYPE_FIX_2D = 2,
    VTP_FIX_TYPE_FIX_3D = 3,
    VTP_FIX_TYPE_GNSS_DR = 4,
    VTP_FIX_TYPE_TIME_ONLY = 5,
} vtp_fix_type_t;

typedef enum {
    VTP_STATUS_OK = 0,
    VTP_STATUS_UNSUPPORTED_OPCODE = 1,
    VTP_STATUS_BAD_PARAMS = 2,
    VTP_STATUS_TABLE_FULL = 3,
    VTP_STATUS_RATE_EXCEEDED = 4,
    VTP_STATUS_BUSY = 5,
    VTP_STATUS_NEEDS_ENCRYPTION = 6,
    VTP_STATUS_UNKNOWN_HANDLE = 7,
} vtp_status_t;

typedef enum {
    VTP_SUB_MODE_EVERY_FRAME = 0,
    VTP_SUB_MODE_PERIODIC = 1,
    VTP_SUB_MODE_ON_CHANGE = 2,
    VTP_SUB_MODE_EVERY_NTH = 3,
} vtp_sub_mode_t;

typedef enum {
    VTP_CHANNEL_LAP_TIME = 1,
    VTP_CHANNEL_LAST_LAP_TIME = 2,
    VTP_CHANNEL_BEST_LAP_TIME = 3,
    VTP_CHANNEL_DELTA_BEST = 4,
    VTP_CHANNEL_PREDICTED_LAP_TIME = 5,
    VTP_CHANNEL_LAP_NUMBER = 6,
    VTP_CHANNEL_SPEED = 7,
    VTP_CHANNEL_SESSION_DISTANCE = 8,
    VTP_CHANNEL_SESSION_TIME = 9,
} vtp_channel_t;

typedef enum {
    VTP_PHY_LE_1M = 1,
    VTP_PHY_LE_2M = 2,
    VTP_PHY_LE_CODED = 3,
} vtp_phy_t;

#define VTP_GPS_VALIDITY_T_UTC (1u << 0)
#define VTP_GPS_VALIDITY_T_UTC_RESOLVED (1u << 1)
#define VTP_GPS_VALIDITY_POSITION (1u << 2)
#define VTP_GPS_VALIDITY_ALT_MSL (1u << 3)
#define VTP_GPS_VALIDITY_ALT_ELLIPSOID (1u << 4)
#define VTP_GPS_VALIDITY_VELOCITY (1u << 5)
#define VTP_GPS_VALIDITY_HEAD_MOT (1u << 6)
#define VTP_GPS_VALIDITY_H_ACC (1u << 7)
#define VTP_GPS_VALIDITY_V_ACC (1u << 8)
#define VTP_GPS_VALIDITY_S_ACC (1u << 9)
#define VTP_GPS_VALIDITY_P_DOP (1u << 10)
#define VTP_GPS_VALIDITY_NUM_SV (1u << 11)

#define VTP_FIX_FLAGS_DIFFERENTIAL (1u << 0)
#define VTP_FIX_FLAGS_RTK_FLOAT (1u << 1)
#define VTP_FIX_FLAGS_RTK_FIXED (1u << 2)
#define VTP_FIX_FLAGS_CLOCK_DISCIPLINED (1u << 3)
#define VTP_FIX_FLAGS_SOLUTION_EPOCH (1u << 4)

#define VTP_CAPABILITIES_GPS (1u << 0)
#define VTP_CAPABILITIES_CAN (1u << 1)
#define VTP_CAPABILITIES_IMU (1u << 2)
#define VTP_CAPABILITIES_MONITOR (1u << 3)
#define VTP_CAPABILITIES_CONTROL (1u << 4)
#define VTP_CAPABILITIES_CAN_FD (1u << 5)
#define VTP_CAPABILITIES_MASKED_SUBSCRIPTIONS (1u << 6)
#define VTP_CAPABILITIES_ON_CHANGE_SUBSCRIPTIONS (1u << 7)

#define VTP_MONITOR_VALIDITY_PRESENT (1u << 0)

#define VTP_LINK_VALIDITY_ATT_MTU (1u << 0)
#define VTP_LINK_VALIDITY_LL_DATA_LENGTH (1u << 1)
#define VTP_LINK_VALIDITY_CONN_PARAMS (1u << 2)
#define VTP_LINK_VALIDITY_PHY (1u << 3)

#endif /* VTP1_GENERATED_H */
